name: Setup
description: Setup git, node, pnpm and install deps

runs:
  using: "composite"
  steps:
    - name: Git Config
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      shell: bash

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ env.NODE_VERSION || '24' }}
        registry-url: https://registry.npmjs.org/
        cache: 'pnpm'

    - name: Setup PNPM and Install Deps
      uses: pnpm/action-setup@v4
      with:
        version: ${{ env.PNPM_VERSION || '10' }}
        run_install: |
          - args: [--frozen-lockfile]